version: '3'

services:
  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins
    ports:
      - "4008:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home:
